export const visitSignIn = () => cy.visit("/sign-in")
export const getEmail = () => cy.get("#email")
export const getPassword = () => cy.get("#password")
export const getPasswordError = () => cy.get("#password-error")
export const getDropdown = () => cy.get("#dropdown", { timeout: 5000 })
export const getAddWorkspaceInput = () => cy.get('input[name="addWorkspace"]')
export const getAddWorkspaceBtn = () => cy.get('button[name="addWorkspace"]')
export const getSections = () => cy.get("#sections")
export const getAddSectionBtn = () => cy.get("#add-section")
export const getTestNameInput = () =>
  cy.get('input[placeholder="Enter Test Name*"]')
export const getTextArea = () => cy.get("textarea")
export const getSubmitBtn = () => cy.get('[data-cy="submit"]')
export const getSectionCards = () => cy.get("#section-card")
export const getSectionCardByClass = () => cy.get(".sectionCard")
export const getSectionName = () => cy.get(".sectionName")
export const getAddQuestionBtn = () =>
  cy.get("#add-question", { timeout: 8000 })
export const geth1 = () => cy.get("h1")
export const getQuestionWithDropdown = () =>
  cy.get("#Question").get("#dropdown-container")
export const getQlEditorWrapper = () => cy.get("#question-editor #quill-editor")
export const getQlEditor = () => cy.get(".ql-editor")
export const getQlEditorInput = () =>
  cy.get('input[placeholder="Write your option here"]')
export const getSaveAndExit = () => cy.get("#save-and-exit")
export const getSaveAndAddMore = () => cy.get("#save-and-add-more")
export const getTests = () => cy.get("#tests")
export const getSettings = () => cy.get("#Settings")
export const getAddTestBtn = () => cy.get("#add-test")
export const getAssesmentNameInput = () =>
  cy.get('input[placeholder="Enter assessment name"]')
export const getNextBtn = () => cy.get("#next-button")
export const getStepsTabs = () => cy.get(".stepsTab")
export const getNumberOfQuestionsInput = () => cy.get("input#no-of-qu")
export const getTimeInput = () => cy.get("input#time")
export const getAssesmentSubmitBtn = () => cy.get("button#submit-button")
export const getAssesmentQlEditorWrapper = () => cy.get("#quill-editor")
export const getInviteMemberBtn = () => cy.get("#invite-member")
export const getDialogWrapper = () => cy.get("#dialog-wrapper")
export const getResetPasswordPopupHeading = () => cy.get("#dialog-wrapper h2")
export const getEmailInput = () => cy.get('input[name="email"]')
export const getAddMemberModal = () => cy.get("div").get("#add-member-modal")
export const getInviteBtn = () => cy.get("#invite-button")
export const getAssessmentsPageTitle = () => cy.get("#assessments-page-title")
export const getInvitePopup = () => cy.get("#invite-popup-open0")
export const getFirstName = () => cy.get("#firstName")
export const getLastName = () => cy.get("#lastName")
export const getConfirmPassword = () => cy.get("#confirmPassword")
export const getAddButton = () => cy.get("#add-button")
export const getSignUpPageTitle = () => cy.get("#signup-page-title")
export const getTestHeading = () => cy.get("#tests-heading")
export const getCancelButton = () => cy.get("#cancel-button")
export const getDialogHeader = () => cy.get('[data-cy="dialog-header"]')
export const getActiveSectionCard = () => cy.get(".activeSectionCard")
export const getSubmitButtonById = () => cy.get("#submit-button")
export const getSectionDetailsHeading = () => cy.get("#section-details-heading")
export const getSectionSearch = () => cy.get("#section-search")
export const getQuestionCardWrapper = () => cy.get("#question-card-wrapper")
export const getOptionWrapper = () => cy.get("#options-wrapper")
export const getQuestionType = () => cy.get("#question-type")
export const getAddEditSectionTitleError = () =>
  cy.get("#addEditSection-title-error")
export const addEditSectionDescError = () =>
  cy.get("#addEditSection-description-error")
export const duplicateTitleError = () => cy.get("#duplicete-title-error")
export const getMembersHeading = () => cy.get(".membersHeading")
export const getMemberDialogHeader = () => cy.get('[data-cy="dialog-header"]')
export const getCancelBtn = () => cy.get("#cancel-add-button")
export const getJoinedMemberHeading = () => cy.get("#joined-member-heading")
export const getInvitedMemberHeading = () => cy.get("#invited-member-heading")
export const getResendMemberInviteBtn = () => cy.get("#resend-member-invite")
export const getToaster = () => cy.get(".Toastify__toast--success")
export const getTableRow = () => cy.get("#table-row #table-td")
export const getBadgeTag = () => cy.get('[data-cy="badge-tag"]')
export const getGeneral = () => cy.get("#General")
export const getWorkspaces = () => cy.get("#Workspaces")
export const getJoinedMembers = () => cy.get("#Joined_Members")
export const getInvitedMembers = () => cy.get("#Invited_Members")
export const getResetPasswordPopup = () => cy.get(".resetPassOpenPopUpLink")
export const getOldPassword = () => cy.get("#oldPassword")
export const getNewPassword = () => cy.get("#newPassword")
export const getConfirmNewPassword = () => cy.get("#confirmNewPassword")
export const getInputContainerWrapper = () => cy.get(".input-container-wrapper")
export const getLabel = () => cy.get("label")
export const getConfirmPasswordError = () => cy.get("#confirm-password-error")
export const getNewPasswordError = () => cy.get("#new-password-error")
export const getSectionLSWrapper = () => cy.get(".sectionLSWrapper")
export const getRegistrationButtonId = () => cy.get("[data-cy='submitButton']")
export const getOTPVerificationHeader = () => cy.get('[data-cy="header"]')
export const getEmailIDOfCandidate = () => cy.get('[data-cy="email"]')
export const getResendOTP = () => cy.get('[data-cy="resendOTP"]')
export const getResendText = () => cy.get("[data-cy='resendText']")
export const getResendButton = () => cy.get('[data-cy="resendButton"]')
export const getToastMessage = () => cy.get(".Toastify__toast")
export const getOTPFirstInputField = () => cy.get('input[name="field-1"]')
export const getOTPSecondInputField = () => cy.get('input[name="field-2"]')
export const getOTPThirdInputField = () => cy.get('input[name="field-3"]')
export const getOTPFourthInputField = () => cy.get('input[name="field-4"]')
export const getSectionHeading = () => cy.get('[data-cy="testSectionHeading"]')
export const getTestSectionContent = () =>
  cy.get('[data-cy="testSectionContent"]')
export const getInstructionSectionHeading = () =>
  cy.get('[data-cy="instructionSectionHeading"]')
export const getInstructionSectionContent = () =>
  cy.get('[data-cy="instructionSectionContent"]')
export const getGoodLuckMessageText = () =>
  cy.get('[data-cy="goodLuckMessageText"]')
export const getBeginAssessmentButton = () => cy.get("#start")
export const getRemainingTime = () => cy.get('[data-cy="timeRemaining"] span')
export const getQuestionSectionHeading = () =>
  cy.get('[data-cy="questionSection"] span')
export const getQuestion = () => cy.get('[data-cy="questionSection"] p')
export const getAnswerSectionHeading = () =>
  cy.get('[data-cy="answerSection"] div')
export const getAnswer = () => cy.get('[data-cy="answerSection"] textarea')
export const getcoolDownCard = () => cy.get(".w-coolDownCard")
export const getAnswerSectionLabel = () =>
  cy.get('[data-cy="answerSection"] label')
export const getStepperContents = () => cy.get(".contents")
export const getGroupByTestId = () => cy.get("#group-by-tests")
export const getVeriticalIconId = () => cy.get("#vertical-icon")
export const getCopyLinkId = () => cy.get('[data-cy="copy-link"]')
export const getEmailInputField = () => cy.get(".inviteInput")
export const getGroupByItemTest = () => cy.get(".groupByItemTest")
export const getInstructionHeading = () => cy.get('[data-cy="heading"]')
export const getNavGuideResult = () => cy.get("#nav-guide-results")
export const getNavGuideAssessment = () => cy.get("#nav-guide-assessments")
export const getNavGuideGeneral = () => cy.get("#nav-guide-general")
export const getSideNavUserName = () => cy.get("#sidenav-username")
export const getSideNavUserEmail = () => cy.get("#sidenav-user-email")
export const getSideNavUserAvatar = () => cy.get("#sidenav-user-avatar")
export const getSideNavLogoutBtn = () => cy.get("#logout-button")
export const getForgetPasswordCard = () => cy.get("#forget-password-card")
export const getForgetPasswordHeader = () => cy.get("#forget-pass-header")
export const getInput = () => cy.get("input")
export const getButton = () => cy.get("button")
export const getEmailErrorById = () => cy.get("#email-error")
export const getResetPassword = () => cy.get("#reset-password")
export const getBackToLogIn = () => cy.get("#back-to-login")
export const getHr = () => cy.get("hr")
export const getImg = () => cy.get("img")
export const getEmailInfo = () => cy.get("#enter-mail-info")
export const getDialogCloseIcon = () => cy.get("#dialog-close-icon")
export const getGroupByItems = () => cy.get('[data-cy="group-by-item-test"]')
export const getDescendSort = () => cy.get("#descend", { timeout: 60000 })
export const getSortFilterBody = () =>
  cy.get("#sort-filter-body", { timeout: 60000 })
export const getTotalItemValue = () =>
  cy.get("#total-items-value", { timeout: 60000 })
export const getElementInsideOfDropdown = () =>
  cy.get(".dropdownButton span span")
export const getGroupByTestItems = () => cy.get("#group-by-test-items")
export const getCandidateName = () =>
  cy.get(".candidate-name", { timeout: 6000 })
export const sortFilterContainer = () => cy.get("#sort-filter-container")
export const getDropdownButton = () => cy.get(".dropdownButton")
export const getDivInsideTheList = () => cy.get("li div")
export const getDropdownOption = () => cy.get(".dropdown-option")
export const getNotSelected = () => cy.get(".not-selected")
export const getResendInviteCandidate = () =>
  cy.get('[data-cy="resend-invite"]')
export const getAscSort = () => cy.get("#ascend")
export const getQuetion = () => cy.get(".question")
export const getTest = () => cy.get("#Test")
export const getInputTextArea = () => cy.get('input[type="textarea"]')
export const getDeleteQuestion = () => cy.get('[data-cy="delete-question"]')
export const getCheckbox = () => cy.get('input[type="checkbox"]')
export const getOptEditorInput = () => cy.get("#optionEditor input")
export const getDeleteOption = () => cy.get("#delete-option")
export const getSvg = () => cy.get("svg.h-6")
export const getTitle = () => cy.get("#title", { timeout: 20000 })
export const getBackButton = () => cy.get("#back-button", { timeout: 8000 })
export const getAnchorTag = () => cy.get("a")
export const getFindTests = () => cy.find("#tests", { timeout: 6000 })
export const getTestNameNavigation = () => cy.get(".test-name-navigation")
export const getName = () => cy.get("#name")
export const getInvitePopupOpenText = () => cy.get("#invite-popup-open-text")
export const getTestPreviewAssessDetail = () =>
  cy.get("#test-preview-assessment-details")
export const getTestPrewSelectedTest = () =>
  cy.get("#test-preview-selected-tests")
export const getDescription = () => cy.get("#description")
export const getTotalTime = () => cy.get("#totalTime")
export const getTotalSections = () => cy.get("#totalSection")
export const getTableTh = () => cy.get("#table-th")
export const getAssessmentHeader = () => cy.get('[data-cy="Assessment"]')
export const getTestHeader = () => cy.get('[data-cy="Test"]')
export const getCreatedOnHeader = () => cy.get('[data-cy="Created On"]')
export const getCreatedByHeader = () => cy.get('[data-cy="Created By"]')
export const getActionHeader = () => cy.get('[data-cy="Action"]')
export const getChipGroup = () => cy.get(".chip-group")
export const getSectionCountBtn = () => cy.get("#section-count-button")
export const getToastBody = () => cy.get(".Toastify__toast-body")
export const getInviteMore = () => cy.get("#invite-more")
export const getInviteInput = () => cy.get(".inviteInput")
export const getDeleteTest = () => cy.get(".deleteTest")
export const getConfirmDelete = () => cy.get("#confirm-delete")
export const getToastifyCloseBtn = () => cy.get(".Toastify__close-button")
export const getAssesPageTitle = () => cy.get("#add-assessment-page-title")
export const getSectionInDiv = () => cy.get("div#section")
export const getBackBtnInBtn = () => cy.get("button#back-button")
export const getNextBtnInBtn = () => cy.get("button#next-button")
export const getCandidateByDataCy = () => cy.get('[data-cy="candidateName"]')
export const getResultDetails = () => cy.get('[data-cy="result-details"]')
export const getChipTag = () => cy.get('[data-cy="chip-tag"]')
export const getListItem = () => cy.get(".list-item")
export const getGivenAnswer = () => cy.get('[data-cy="givenAnswers"]')
export const getSkippedContainer = () => cy.get('[data-cy="skipped-container"]')
export const getBackButtonByDataCy = () => cy.get('[data-cy="back-button"]')
export const getCorrectAnswer = () => cy.get('[data-cy="correct-answer"]')
export const getPaginationDropdownButton = () =>
  cy.get(".paginationInfo button")
export const getPaginationDropdown = () =>
  cy.get('[data-cy="pagination-dropdown"]')
export const getPaginationDetails = () =>
  cy.get('[data-cy="pagination-details"]')
export const getPaginationRange = () => cy.get(".pagination")
export const getSideNavFooterDropdownButton = () =>
  cy.get(".sidenav-footer-menu")
export const getMyProfileButton = () => cy.get("[data-cy='my-profile']")
export const getMyProfileTitle = () => cy.get("#my-profile-page-title")
export const getEditProfileButton = () => cy.get("#edit-user")
export const getUserProfileDetails = () =>
  cy.get("[data-cy='userProfileDetails']")
export const getSaveButton = () => cy.get("#save")
export const getFirstNameInput = () => cy.get('input[name="first-name"]')
export const getLastNameInput = () => cy.get('input[name="last-name"]')
export const getChangePasswordButton = () =>
  cy.get("[data-cy='change-password']")
export const getLogoutButton = () => cy.get("[data-cy='logout']")
export const getCancelEditWorkspaceBtn = () => cy.get("#cancel-edit-workspace")
export const getSaveWorkspaceBtn = () => cy.get("#save-workspace")
export const getEditWorkspaceBtn = () => cy.get("#edit-workspace")
export const getCurrentWorkspace = () => cy.get("#current-workspace")
export const getLeaveWorkspaceBtn = () => cy.get("#leave-workspace")
export const getWorkspaceNameInput = () => cy.get("#workspace-name-input")
export const getWorkspaceInputError = () => cy.get("#workspace-input-error")
export const getH2 = () => cy.get("h2")
export const getH3 = () => cy.get("h3")
export const getSettingsHeading = () => cy.get("#settings-heading")
export const getLogoutBtn = () => cy.get('[data-cy="logout"]')
export const getTable = () => cy.get("#table-row #table-td")
export const getChangeRoleId = () => cy.get("#change-role-dialog")
export const getRoleChangeContent = () => cy.get('[data-cy="role-heading"]')
export const getDropdownOptions = () => cy.get(".dropDownSelect")
export const getDialogFooter = () => cy.get("[data-cy='dialog-footer']")
export const getFeedbackHeader = () =>
  cy.get("[data-cy='feedback-form-header']")
export const getFeedbackFooter = () =>
  cy.get("[data-cy='feedback-form-footer']")

export const getFeedbackQuestion = () => cy.get("[data-cy='feedback-question']")
