export const commonConstants = {
  name: 'Name',
  cancel: 'Cancel',
  delete: 'Delete',
  backButton: 'Back',
  nextButton: 'Next',
  prevoiusButton: 'Previous',
  removeButton: 'Remove',
  addButton: 'Add',
  byText: 'By',
  continue: 'Continue',
  proceed: 'Proceed',
  total: 'Total',
  placeholderForOptionInput: 'Write your option here',
  sortAscending: 'Sort Ascending',
  sortDescending: 'Sort Descending',
  invalidLinkSVG: 'Invalid Link SVG',
  useSetting: 'Use setting',
  settings: 'Settings',
  groupByCandidate: 'Group By Candidate',
  results: 'Results',
  goToDashboard: 'Go to Dashboard',
  checkOrder: 'Check Order',
  complete: 'Complete',
  pending: 'Pending',
  createTest: 'Creating Test',
  submit: 'Submit',
  adding: 'Adding...',
  add: 'Add',
  cancelAddTest: 'Cancel Add Test',
  previousTab: 'Previous Tab',
  nextTab: 'Next Tab',
  logo: 'logo',
  saveAndExit: 'Save & Exit',
  saveAndAddMore: 'Save & Add More',
  logout: 'Logout',
  enterSectionName: 'Enter Section Name',
  enterSectionDesc: 'Enter Section Description',
  enterTestName: 'Enter test name',
  totalQuestion: 'Total Questions',
  verify: 'Verify',
  email: 'Email',
  createPassword: 'Create Password',
}
export const sideNav = {
  sideNavHeading: 'Quiz',
}
export const candidateHeader = {
  headerHeading: 'Quiz',
}
export const members = {
  inviteMembers: 'Invite Member',
  firstName: 'First Name',
  lastName: ' Last Name',
  name: 'Name',
  role: 'Role',
  members: 'Members',
  addedOn: 'Added On',
  action: 'Action',
  member: 'member',
}
export const inviteMemeberPopUpConstants = {
  inviteCandidate: 'Invite Candidate',
  closePopUp: 'Close Pop Up',
  enterCandidatesEmail: 'Enter candidate’s email below to invite them for',
  candidateEmail: 'Candidate Email',
  inviteMore: 'Invite More',
  invite: 'Invite',
}
export const testTableItem = {
  inviteMember: 'Invite Member',
  menu: 'Menu',
}
export const logo = {
  kQuizLogo: 'K-Quiz Logo',
}

export const deletePopUp = {
  alert: 'Do you want to delete',
  subAlert: '(All the questions for this section will also be deleted)',
}
export const logIn = {
  signInMessage: 'Sign in to your account',
  signIn: 'Sign In',
  signUp: 'Sign Up',
  signingUp: 'Signing up...',
  AlreadyHaveAnAccount: 'Already have an account?',
  DontHaveAnAccountYet: 'Don’t have an account yet?',
}
export const addQuestion = {
  createOptions: 'Create Options',
  checkOrder: 'Check Order',
  addOptions: 'Add Options',
  addQuestion: 'Add Question',
}

export const sectionsConstants = {
  addSection: 'Add Section',
  totalQuestions: 'Total Questions:',
  noQuestionAlert: 'No questions found. Add your first question',
  noRecordFound: 'No Record Found',
  sort: 'Sort',
  dropdown: 'Select',
  expand: 'Expand',
  search: 'Search Question',
  sectionName: 'Section',
}
export const testsConstants = {
  addTestbutton: 'Add Assessment',
  testDetailsText: 'Test Details',
  descriptionText: 'Description',
  totalTimeText: 'Total Time',
  totalSectionsText: 'Total Sections',
  selectedSctionText: 'Selected Sections',
  sectionText: 'Section',
  questions: 'Questions',
  totalQuestionsText: 'Total Questions',
  assessments: 'Assessments',
  srNoText: 'S No.',
  testListColumnLabel: 'Test',
  createdOn: 'Created on',
  created: 'Created',
  actionsText: 'Actions',
  noTestFound: 'No Test Found',
  noCandidateForTest: 'No candidate has attempted this test',
  candidateAlreadyInvited: 'Candidate has already been invited for this test',
  candidateInvited: 'Candidates Invited',
  writeDescriptionOfTest: 'Write Description of Test',
  testName: 'test',
  reinvited: 'Candidate Invited Successfully',
}
export const componentGlobalConstants = {
  totalCounts: 'Total Counts',
  selected: 'Selected',
}
export const routeFiles = {
  sections: 'Sections',
  options: 'Options',
}

export const statusCheck = {
  success: 'Success',
  commonError: 'Something went wrong. Please try again.',
  deletedSuccess: 'Deleted Successfully...!',
  noEmailsInvite: 'No emails to invite',
  selectCorrOption: 'Select the Correct Option',
  descIsReq: 'Description is required',
  nameIsReq: 'Name is required',
  sectionAddedSuccess: 'Section added successfully..!',
  maxOptions: 'you can add maximum six options.',
  testDependentWarning:
    "Can't be deleted as you have to delete the test containing this section first",
  duplicate: 'Duplicate Title',
  testAddedSuccessFully: 'Test added successfully..',
  testAlreadyExist: 'Test name already exist.',
  emailIsInvalid: 'Email is invalid',
  passIsReq: 'Password is required',
  passIsInvalid: 'Password is invalid',
  questionAddedSuccess: 'Question Added Successfully',
  questionNotAdded: 'Question Not Added Successfully',
  firstNameReq: 'firstName is required',
  lastNameReq: 'lastName is required',
  emailIsReq: 'email is required',
  roleIdIsReq: 'roleId is required',
  memberAddedSuccess: 'Member Added Successfully..!',
  erroSendingOtp: 'Error in sending OTP..',
  otpSent: 'Otp sent. Please check your email',
  correctOtp: 'Please enter correct OTP',
  resendPasswordSuccess: 'New password has been sent to email successfully',
  resendPasswordError: 'Account not found. Please enter valid email',
  enteredReenteredPassword: 'Entered and Re-Entered Password should be equal.',
  userNotFound: 'User Not Found',
}
export const resultConstants = {
  order: 'Order',
  test: 'Test',
  totalInvited: 'Invited',
  totalAttended: 'Attended',
  noTestAlert: 'No test found. Add your test first',
  srNo: 'Sr.No',
  invitedBy: 'Invited By',
  result: 'Result',
  review: 'Review',
  status: 'Status',
  inactive: 'Inactive',
  active: 'Active',
  startedAt: 'Started At',
  correct: 'Correct',
  skipped: 'Skipped',
  total: 'Total',
}
export const forgotPasswordConstants = {
  header: 'Forgot password?',
  enterEmail: 'Enter your email to retrieve your password.',
  resetPassword: 'Reset Password',
  backToLogin: 'Back to login',
  enterEmailPlaceholder: 'Enter Email',
}
export enum QuestionStatus {
  notViewed = 'NOT_VIEWED',
  viewed = 'VIEWED',
  skipped = 'SKIPPED',
  answered = 'ANSWERED',
}
export const candidateExamConstants = {
  time: 'Time',
  timeRemaining: 'Time Remaining',
  timeLimit: 'Time Limit',
  takeBreak: 'Take A Break!',
  cheers: 'Cheers! Angular Questions Completed - two more to go',
  startNewSection: 'Start New Section',
  cooldown: 'Cooldown Image',
  testCompleted: 'Congratulations! You have completed the exam',
  candidateContact: 'We will contact you soon',
  assessmentDetails: 'Assessment Details',
  assessmentTests: 'Assessment Tests',
  assessmentEnd: 'Assessment Ended',
  endAssessment: 'End Assessment SVG',
  wrongLink: 'Wrong Link',
  minutes: 'Mins',
  description: 'Description',
  total: 'Total',
  question: 'Question',
  questions: 'Questions',
  endTest: 'End Test',
  nextSection: 'Next Section',
  candidateAcceptance:
    'I understand that once I begin the assessment I cannot leave and  return to this assessment at a later time.',
  beginAssessment: 'Begin Assessment',
  instructions: 'Instructions',
  startSection: 'Start Now',
  candidateLogo: 'Candidate Logo',
  info: 'Info',
  noOfQuestions: 'No. of Questions',
  candidateTestCreated: 'created',
  error: 'error',
  candidateCreateError: 'Candidate Create Error..!',
  candidateTestCreateError: 'Candidate Test Create Error..!',
  errorUpdatingTestLink: 'Error updating test link..!',
  errorCreatingSectionInTest: 'Error creating section in test ..',
  candidateInsWelcome: 'Welcome',
}
export const cypress = {
  email: 'copods.demo.sendgrid@gmail.com',
  password: 'kQuiz@copods',
  step1: 'Step 1',
  step2: 'Step 2',
  step3: 'Step 3',
  testDetails: 'Assessment Details',
  selectSections: 'Select Sections',
  preview: 'Preview',
  next: 'Next',
  remove: 'Remove',
  back: 'Back',
  duplicateTitle: 'Duplicate Title',
  saveAndAddMore: 'Save & Add More',
  addMember: 'Invite Member',
  name: 'Name',
  description: 'Description',
  totalTime: 'Total Time',
  useRef: 'What is useRef() ?',
  useRefAns: 'It allows you to persist values between renders.',
  useMemo: 'What is useMemo() ?',
  useMemoAns:
    'The useMemo Hook can be used to keep expensive, resource intensive functions from needlessly running.',
}
export const toastConstants = {
  addTest: 'Enter Name to add test',
  resendMemberInvitation: 'Invitation Sent Successfully..!',
  enterDescription: 'Enter description to add test',
  addSection: 'Add sections to add test',
  enterQuestion: 'Enter the Question',
  enterOption: 'Enter all the Options',
  firstNameRequired: 'First Name is required',
  lastNameRequired: 'Last Name is required',
  emailRequired: 'Email is required',
  roleRequired: 'Role is required',
  correctEmail: 'Please provide a valid email address',
  memberAdded: 'Member Added Successfully..!',
  memberAlreadyExist: 'Member with this email id already exists!',
  signUpSuccessfull: 'Sign Up successfully',
  workspaceNameIsRequired: 'Workspace name is required',
}
export const otpConstants = {
  header: 'OTP Verification',
  enterOTP: 'Enter the OTP sent to',
  resend: 'Resend',
  didntGetCode: "Didn't get a code",
  resendCodeIn: 'Resend code in',
  otp: 'OTP',
}
export const settings = {
  settings: 'Settings',
  clickToChange: 'Click to change',
  resetPas: 'Reset Password',
  passNotMatch: 'Password do not match',
  enterNewPass: 'Enter New Password',
  reEnterPass: 'Re-Enter Password',
  enterOldPassword: 'Enter Old Password',
  minPasswordLimit: 'Password should have minimum 8 characters',
  passShouldNotBeSame: 'Current Password and New Password should not be same',
}
export const tabs = {
  general: 'General',
  workspace: 'Workspaces',
}
