export const routes = {
  dashboard: '/dashboard',
  signIn: '/sign-in',
  signUp: '/sign-up',
  instructions: 'instructions',
  tests: '/assessments',
  sections: '/sections',
  addQuestion: '/add-question',
  addTest: '/assessments/add-assessment',
  resultGroupTest: '/results/groupByTests',
  members: '/members',
  settings: '/settings',
  forgotPassword: '/forgot-password',
  endExam: '/end-assessment',
}
