export const routes = {
  dashboard: "/dashboard",
  signIn: "/sign-in",
  signUp: "/sign-up",
  instructions: "instructions",
  assessments: "/assessments",
  tests: "/tests",
  addQuestion: "/add-question",
  addAssessment: "/assessments/add-assessment",
  resultGroupTest: "/results/groupByTests",
  members: "/members",
  generalSettings: "/settings/general",
  workspaceSetting: "/settings/workspace",
  settings: "/settings",
  forgotPassword: "/forgot-password",
  endExam: "/end-assessment",
  unauthorized: "/unauthorized",
  myProfile: "/my-profile",
  logout: "/logout",
  feedback: "/feedback",
}
