import { logIn, settings, toastConstants } from '~/constants/common.constants'

const firstName = 'John'
const lastName = 'Doe'
const memberEmail = 'john@example.com'
const workspaceName = 'Copods workspace'

describe('Test for Sign Up page', () => {
  beforeEach('/sign-up', () => {
    cy.visit('/sign-up')
  })
  it('check toster showing a error if try to submit without filling first name input field', () => {
    cy.get('#lastName').clear().type(lastName).should('have.value', lastName)
    cy.get('#email').clear().type(memberEmail).should('have.value', memberEmail)
    cy.get('#workspace')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(workspaceName)
      .should('have.value', workspaceName)
    cy.get('#add-button').should('have.text', logIn.signUp).click()
    cy.get('#firstName-error').should(
      'have.text',
      toastConstants.firstNameRequired
    )
  })
  it('check toster showing a error if try to submit without filling last name input field', () => {
    cy.get('#firstName')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(firstName)
      .should('have.value', firstName)
    cy.get('#email')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(memberEmail)
      .should('have.value', memberEmail)
    cy.get('#workspace')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(workspaceName)
      .should('have.value', workspaceName)
    cy.get('#add-button').should('have.text', logIn.signUp).click()
    cy.get('#lastName-error').should(
      'have.text',
      toastConstants.lastNameRequired
    )
  })
  it('check toster showing a error if try to submit without filling email input field', () => {
    cy.get('#firstName')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(firstName)
      .should('have.value', firstName)
    cy.get('#lastName')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(lastName)
      .should('have.value', lastName)
    cy.get('#workspace')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(workspaceName)
      .should('have.value', workspaceName)
    cy.get('#add-button').should('have.text', logIn.signUp).click()
    cy.get('#email-error').should('have.text', toastConstants.emailRequired)
  })
  it('check toster showing a error if try to submit without filling workspace name input field', () => {
    cy.get('#firstName')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(firstName)
      .should('have.value', firstName)
    cy.get('#lastName')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(lastName)
      .should('have.value', lastName)
    cy.get('#email')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(memberEmail)
      .should('have.value', memberEmail)

    cy.get('#add-button').should('have.text', logIn.signUp).click()
    cy.get('#workspace-error').should(
      'have.text',
      toastConstants.workspaceNameIsRequired
    )
  })
  it('Checks if password and re-enter password input fields input values not matched then thowing a proper error', () => {
    cy.get('#firstName')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(firstName)
      .should('have.value', firstName)
    cy.get('#lastName')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(lastName)
      .should('have.value', lastName)
    cy.get('#email')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(memberEmail)
      .should('have.value', memberEmail)
    cy.get('#workspace')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(workspaceName)
      .should('have.value', workspaceName)
    cy.get('#Password').should('be.visible').clear().type('newPassword')
    cy.get('#confirmPassword')
      .should('be.visible')
      .clear()
      .type('confirmPassword')
    cy.get('#add-button').should('have.text', logIn.signUp).click()
    cy.get('#Confirm-password-error').should('have.text', settings.passNotMatch)
  })
  it('signing up successfully', () => {
    cy.get('#firstName')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(firstName)
      .should('have.value', firstName)
    cy.get('#lastName')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(lastName)
      .should('have.value', lastName)
    cy.get('#email')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(memberEmail)
      .should('have.value', memberEmail)
    cy.get('#workspace')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(workspaceName)
      .should('have.value', workspaceName)
    cy.get('#Password').should('be.visible').clear().type('newPassword')
    cy.get('#confirmPassword').should('be.visible').clear().type('newPassword')
    cy.get('#add-button').should('have.text', logIn.signUp).click()
    cy.get('.Toastify__toast', { timeout: 6000 }).should(
      'have.text',
      toastConstants.signUpSuccessfull
    )
  })
  it('trying to sign up but member is already exist', () => {
    cy.get('#firstName')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(firstName)
      .should('have.value', firstName)
    cy.get('#lastName')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(lastName)
      .should('have.value', lastName)
    cy.get('#email')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(memberEmail)
      .should('have.value', memberEmail)
    cy.get('#workspace')
      .should('be.visible', { timeout: 60000 })
      .clear()
      .type(workspaceName)
      .should('have.value', workspaceName)
    cy.get('#Password').should('be.visible').clear().type('newPassword')
    cy.get('#confirmPassword').should('be.visible').clear().type('newPassword')
    cy.get('#add-button').should('have.text', logIn.signUp).click()
    cy.get('.Toastify__toast').should(
      'have.text',
      toastConstants.memberAlreadyExist
    )
  })
})
