import { StyleSheet } from "@react-pdf/renderer"

export const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#FFFFFF",
    padding: 10,
  },
  header: {
    flexDirection: "column",
    alignContent: "flex-start",
    justifyContent: "flex-start",
    textAlign: "left",
    width: "100%",
  },
  candidateName: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#353988",
    marginBottom: 10,
  },
  sectionContainer: {
    fontSize: 14,
    backgroundColor: "#E6E6E6",
    borderRadius: 5,
    marginBottom: 10,
  },
  sectionHeader: {
    backgroundColor: "#353988",
    color: "#FFFFFF",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    padding: 10,
    borderRadius: 5,
    fontSize: 14,
  },
  sectionResult: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "flex-start",
  },
  sectionContent: {
    padding: 10,
  },
  questionContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 5,
    padding: 10,
    flexDirection: "row",
    marginVertical: 5,
    alignItems: "flex-start",
    gap: 5,
  },
  questionMainContainer: {
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    width: "100%",
  },
  questionContentContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignContent: "center",
    width: "100%",
  },
  questionContentTypeContainer: {
    fontSize: 10,
    borderRadius: 5,
    border: 2,
    paddingVertical: 2,
    borderColor: "#E6E6E6",
    paddingHorizontal: 3,
  },
  answerContentContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignContent: "center",
    width: "100%",
  },
  questionText: {
    padding: 5,
    fontSize: 12,
    fontWeight: "bold",
  },
  answerText: {
    backgroundColor: "#F9FAFB",
    borderRadius: 5,
    border: 2,
    marginVertical: 5,
    padding: 5,
    borderColor: "#F3F4F6",
    width: "100%",
    fontSize: 12,
    fontWeight: "bold",
  },
  correct: {
    color: "#00B050",
    fontSize: 10,
    borderRadius: 5,
    border: 2,
    paddingVertical: 2,
    borderColor: "#00B050",
    paddingHorizontal: 3,
  },
  incorrect: {
    fontSize: 10,
    borderRadius: 5,
    border: 2,
    padding: 5,
    borderColor: "#FF0000",
    color: "#FF0000",
  },
  status: {
    fontSize: 12,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
})
