describe('Visiting group by test of results page', () => {

  it('Check if that test is coming on group by test page or not', () => {
    cy.visit('/sign-in')
    cy.get('#email', { timeout: 6000 })
      .clear()
      .type('careers@copods.co')
      .should('have.value', 'careers@copods.co')
    cy.get('#password', { timeout: 6000 })
      .clear()
      .type('kQuiz@copods')
      .should('have.value', 'kQuiz@copods')
    cy.findByRole('button').click()

    cy.get('a', { timeout: 6000 })
      .find('#Group_By_Tests', { timeout: 6000 })
      .should('have.text', 'Results')
      .click()
    cy.location('pathname', { timeout: 60000 }).should('include', '/results')
  })
  it('Check  that if list of candidate is coming after clicking a test in group byt test in results page ', () => {
    cy.visit('/sign-in')
    cy.get('#email', { timeout: 6000 })
      .clear()
      .type('careers@copods.co')
      .should('have.value', 'careers@copods.co')
    cy.get('#password', { timeout: 6000 })
      .clear()
      .type('kQuiz@copods')
      .should('have.value', 'kQuiz@copods')
    cy.findByRole('button').click()

    cy.get('a', { timeout: 6000 })
      .find('#Group_By_Tests', { timeout: 6000 })
      .should('have.text', 'Results')
      .click()
    cy.location('pathname', { timeout: 60000 }).should('include', '/results')
    cy.get('#group-by-test-container', { timeout: 6000 })
      .get('#group-by-items-container', { timeout: 6000 })
      .get('#group-by-item-test', { timeout: 6000 })
      .click()
  })
  it('Check  that if list of attended candidate is coming after clicking a test in group byt test in results page ', () => {
    cy.visit('/sign-in')
    cy.get('#email', { timeout: 6000 })
      .clear()
      .type('careers@copods.co')
      .should('have.value', 'careers@copods.co')
    cy.get('#password', { timeout: 6000 })
      .clear()
      .type('kQuiz@copods')
      .should('have.value', 'kQuiz@copods')
    cy.findByRole('button', { timeout: 6000 }).click()

    cy.get('a')
      .find('#Group_By_Tests', { timeout: 6000 })
      .should('have.text', 'Results')
      .click()
    cy.location('pathname', { timeout: 60000 }).should('include', '/results')
    cy.get('#group-by-test-container', { timeout: 6000 })
      .get('#group-by-items-container', { timeout: 6000 })
      .get('#group-by-item-test', { timeout: 6000 })
      .click()
    cy.get('#Group_By_Tests-test-candidate-list-tab', { timeout: 6000 })
      .get('#tab-title')
      .invoke('text')
      .then((el) => {
        if (el === 'attending') {
          console.log(el, 'el')
        }
      })
  })
})
