describe('Visiting group by test of results page', () => {
  // creating data to test Test list page
  beforeEach('sign-in', () => {
    cy.visit('/sign-in')
    cy.get('input[name="email"]')
      .clear()
      .type(Cypress.env('email'))
      .should('have.focus')
      .should('have.value', Cypress.env('email'))
    cy.get('input[name="password"]')
      .clear()
      .type(Cypress.env('password'))
      .should('have.focus')
      .should('have.value', Cypress.env('password'))
    cy.get('[data-cy="submit"]').click()
    cy.location('pathname').should('include', '/dashboard')
  })

  it('Check if that test is coming on group by test page or not', () => {
    cy.get('a', { timeout: 6000 })
      .find('#Group_By_Tests', { timeout: 6000 })
      .should('have.text', 'Results')
      .click()
    cy.location('pathname', { timeout: 60000 }).should('include', '/results')
  })
  it('Check  that if list of candidate is coming after clicking a test in group byt test in results page ', () => {
    cy.get('a', { timeout: 6000 })
      .find('#Group_By_Tests', { timeout: 6000 })
      .should('have.text', 'Results')
      .click()
    cy.location('pathname', { timeout: 60000 }).should('include', '/results')
    cy.get('#group-by-test-container', { timeout: 6000 })
      .get('[data-cy-="group-by-items-container"]', { timeout: 6000 })
      .get('[data-cy-="group-by-item-test"]', { timeout: 6000 })
      .click()
  })
  it('Check  that if list of attended candidate is coming after clicking a test in group byt test in results page ', () => {
    cy.get('a')
      .find('#Group_By_Tests', { timeout: 6000 })
      .should('have.text', 'Results')
      .click()
    cy.location('pathname', { timeout: 60000 }).should('include', '/results')
    cy.get('#group-by-test-container', { timeout: 6000 })
      .get('[data-cy-="group-by-items-container"]', { timeout: 6000 })
      .get('[data-cy-="group-by-item-test"]', { timeout: 6000 })
      .click()
    cy.get('[data-cy="Group_By_Tests-test-candidate-list-tab"]', { timeout: 6000 })
      .get('#tab-title')
      .invoke('text')
      .then((el) => {
        if (el === 'attending') {
          console.log(el, 'el')
        }
      })
  })
})
