/// <reference types="Cypress"/>
describe('Test for members', () => {
  it('Sample Login', () => {
    cy.visit('/sign-in')
    cy.get('#email')
      .clear()
      .type('careers@copods.co')
      .should('have.value', 'careers@copods.co')
    cy.get('#password')
      .clear()
      .type('kQuiz@copods')
      .should('have.value', 'kQuiz@copods')
    cy.findByRole('button').click()
  })

  it('Test to Direct to members after Login', () => {
    cy.visit('/sign-in')
    cy.get('#email')
      .clear()
      .type('careers@copods.co')
      .should('have.value', 'careers@copods.co')
    cy.get('#password')
      .clear()
      .type('kQuiz@copods')
      .should('have.value', 'kQuiz@copods')
    cy.findByRole('button').click()
    cy.get('a').find('#Members').should('have.text', 'Members').click()
    cy.location('pathname', { timeout: 60000 }).should('include', '/members')
  })

  it('Test for add-members', () => {
    cy.visit('/sign-in')
    cy.get('#email')
      .clear()
      .type('careers@copods.co')
      .should('have.value', 'careers@copods.co')
    cy.get('#password')
      .clear()
      .type('kQuiz@copods')
      .should('have.value', 'kQuiz@copods')
    cy.findByRole('button').click()
    cy.get('a').find('#Members').should('have.text', 'Members').click()
    cy.get('#addMember').should('have.text', '+ Add Member').click()
    cy.get('#firstName').clear().type('hinata').should('have.value', 'hinata')
    cy.get('#lastName').clear().type('hyuga').should('have.value', 'hyuga')
    cy.get('#email')
      .clear()
      .type('hinatahyuga@konoha.co')
      .should('have.value', 'hinatahyuga@konoha.co')
    cy.get('select')
      .select('Recruiter')
      .should('have.value', 'cl4xvjdqs000309jp3rwiefp8')
    cy.get('.justify-end > .bg-primary').click()
    cy.get('.Toastify__toast').find('.Toastify__close-button').click()
    cy.location('pathname', { timeout: 60000 }).should('include', '/members')
  })

  it('Test for add-members cancel button', () => {
    cy.visit('/sign-in')
    cy.get('#email')
      .clear()
      .type('careers@copods.co')
      .should('have.value', 'careers@copods.co')
    cy.get('#password')
      .clear()
      .type('kQuiz@copods')
      .should('have.value', 'kQuiz@copods')
    cy.findByRole('button').click()
    cy.get('a').find('#Members').should('have.text', 'Members').click()
    cy.get('#addMember').should('have.text', '+ Add Member').click()
    cy.get('#cancelAddButton').should('have.text', 'Cancel').click()
    cy.location('pathname', { timeout: 60000 }).should('include', '/members')
  })

  it('Delete member cancel button', () => {
    cy.visit('/sign-in')
    cy.get('#email')
      .clear()
      .type('careers@copods.co')
      .should('have.value', 'careers@copods.co')
    cy.get('#password')
      .clear()
      .type('kQuiz@copods')
      .should('have.value', 'kQuiz@copods')
    cy.findByRole('button').click()
    cy.get('a').find('#Members').should('have.text', 'Members').click()
    cy.wait(3000)
    cy.contains('hinata hyuga')
      .get('#memberRow')
      .within(() => {
        cy.get('#deleteButton').click()
      })
    cy.get('#cancelDeletePopUp').should('have.text', 'Cancel').click()
    cy.location('pathname', { timeout: 60000 }).should('include', '/members')
  })

  it('Delete member test', () => {
    cy.visit('/sign-in')
    cy.get('#email')
      .clear()
      .type('careers@copods.co')
      .should('have.value', 'careers@copods.co')
    cy.get('#password')
      .clear()
      .type('kQuiz@copods')
      .should('have.value', 'kQuiz@copods')
    cy.findByRole('button').click()
    cy.get('a').find('#Members').should('have.text', 'Members').click()
    cy.wait(3000)
    cy.contains('hinata hyuga')
      .get('#memberRow')
      .within(() => {
        cy.get('#deleteButton').click()
      })
    cy.get('#ConfirmDelete').should('have.text', 'Delete').click()
    cy.get('.Toastify__toast').find('.Toastify__close-button  ').click()
    cy.location('pathname', { timeout: 60000 }).should('include', '/members')
  })
})
