/// <reference types="Cypress"/>

import { should } from 'chai'

describe('Test for members', () => {
  it('Sample Login', () => {
    cy.visit('/sign-in')
    cy.get('#email')
      .clear()
      .type('careers@copods.co')
      .should('have.value', 'careers@copods.co')
    cy.get('#password')
      .clear()
      .type('kQuiz@copods')
      .should('have.value', 'kQuiz@copods')
    cy.findByRole('button').click()
  })

  it('Test for recdirect to members page', () => {
    cy.visit('/sign-in')
    cy.get('#email')
      .clear()
      .type('careers@copods.co')
      .should('have.value', 'careers@copods.co')
    cy.get('#password')
      .clear()
      .type('kQuiz@copods')
      .should('have.value', 'kQuiz@copods')
    cy.findByRole('button').click()
    cy.get('a').find('#Members').should('have.text', 'Members').click()
    cy.location('pathname', { timeout: 60000 }).should('include', '/members')
  })

  it('Test for adding a new member', () => {
    cy.visit('/sign-in')
    cy.get('#email')
      .clear()
      .type('careers@copods.co')
      .should('have.value', 'careers@copods.co')
    cy.get('#password')
      .clear()
      .type('kQuiz@copods')
      .should('have.value', 'kQuiz@copods')
    cy.findByRole('button').click()
    cy.get('a').find('#Members').should('have.text', 'Members').click()
    cy.get('#addMember').should('have.text', '+ Add Member').click()
    cy.get('#firstName').clear().type('hinata').should('have.value', 'hinata')
    cy.get('#lastName').clear().type('hyuga').should('have.value', 'hyuga')
    cy.get('#email')
      .clear()
      .type('hinatahyuga@konoha.co')
      .should('have.value', 'hinatahyuga@konoha.co')
    cy.get('select')
      .select('Recruiter')
      .should('have.value', 'cl4xvjdqs000309jp3rwiefp8')
    cy.get('.justify-end > .bg-primary').click()
    cy.get('.Toastify__toast').find('.Toastify__close-button').click()
    cy.location('pathname', { timeout: 60000 }).should('include', '/members')
  })

  it('Test for add-members popUp cancel button', () => {
    cy.visit('/sign-in')
    cy.get('#email')
      .clear()
      .type('careers@copods.co')
      .should('have.value', 'careers@copods.co')
    cy.get('#password')
      .clear()
      .type('kQuiz@copods')
      .should('have.value', 'kQuiz@copods')
    cy.findByRole('button').click()
    cy.get('a').find('#Members').should('have.text', 'Members').click()
    cy.get('#addMember').should('have.text', '+ Add Member').click()
    cy.get('#cancelAddButton').should('have.text', 'Cancel').click()
    cy.location('pathname', { timeout: 60000 }).should('include', '/members')
  })

  it('Test for Delete member popup cancel button', () => {
    cy.visit('/sign-in')
    cy.get('#email')
      .clear()
      .type('careers@copods.co')
      .should('have.value', 'careers@copods.co')
    cy.get('#password')
      .clear()
      .type('kQuiz@copods')
      .should('have.value', 'kQuiz@copods')
    cy.findByRole('button').click()
    cy.get('a').find('#Members').should('have.text', 'Members').click()

    cy.intercept('/members').as('membersPage')
    cy.get('.memberRow').each((item) => {
      cy.contains('hinata hyuga')
        .parent()
        .parent()
        .within(() => {
          cy.get('#deleteButton', { timeout: 60000 })
            .should('be.visible')
            .click()
        })

      cy.get('#cancelDeletePopUp').should('have.text', 'Cancel').click()
      cy.location('pathname', { timeout: 60000 }).should('include', '/members')
    })
  })

  it('Test for Delete member ', () => {
    cy.visit('/sign-in')
    cy.get('#email')
      .clear()
      .type('careers@copods.co')
      .should('have.value', 'careers@copods.co')
    cy.get('#password')
      .clear()
      .type('kQuiz@copods')
      .should('have.value', 'kQuiz@copods')
    cy.findByRole('button').click()
    cy.get('a').find('#Members').should('have.text', 'Members').click()

    cy.intercept('/members').as('membersPage')
    cy.get('.memberRow').each((item) => {
      cy.contains('hinata hyuga')
        .parent()
        .parent()
        .within(() => {
          cy.get('#deleteButton', { timeout: 60000 })
            .should('be.visible')
            .click()
        })
      cy.get('.ConfirmDelete').should('have.text', 'Delete').click()
      cy.get('.Toastify__toast').find('.Toastify__close-button  ').click()
      cy.location('pathname', { timeout: 60000 }).should('include', '/members')
      return false
    })
  })
})
